name: Update Project Site and Commit Log

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 4 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script to update project list
      run: python update_projects.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run script to update commit log
      run: python update_commit_log.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push if files changed
      run: |-
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions-bot@github.com"
        git add projects.md commit-log.md repositories.json
        # Commit only if there are changes
        git commit -m "Automated update of project and commit logs" || echo "No changes to commit"
        git push
